// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYHRDIG0QdrrDOZZm0COIwnUWHDhFXwQ',
    appId: '1:44485603355:web:8bc724ad60025a94c8c8be',
    messagingSenderId: '44485603355',
    projectId: 'guidix-32dc6',
    authDomain: 'guidix-32dc6.firebaseapp.com',
    storageBucket: 'guidix-32dc6.firebasestorage.app',
    measurementId: 'G-KZDY1V0EC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQtOFD7PZVvOhqhYNwzA8TvtR7lmXSS4',
    appId: '1:44485603355:android:4092bb1c18fe73f4c8c8be',
    messagingSenderId: '44485603355',
    projectId: 'guidix-32dc6',
    storageBucket: 'guidix-32dc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoAdGCFStdmg-oxwlS87EMox9aJdgvrNE',
    appId: '1:44485603355:ios:3d7aca0fd132b5f9c8c8be',
    messagingSenderId: '44485603355',
    projectId: 'guidix-32dc6',
    storageBucket: 'guidix-32dc6.firebasestorage.app',
    iosBundleId: 'com.abdelmoneam.guidix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoAdGCFStdmg-oxwlS87EMox9aJdgvrNE',
    appId: '1:44485603355:ios:3d7aca0fd132b5f9c8c8be',
    messagingSenderId: '44485603355',
    projectId: 'guidix-32dc6',
    storageBucket: 'guidix-32dc6.firebasestorage.app',
    iosBundleId: 'com.abdelmoneam.guidix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsYHRDIG0QdrrDOZZm0COIwnUWHDhFXwQ',
    appId: '1:44485603355:web:adb1028859963fe8c8c8be',
    messagingSenderId: '44485603355',
    projectId: 'guidix-32dc6',
    authDomain: 'guidix-32dc6.firebaseapp.com',
    storageBucket: 'guidix-32dc6.firebasestorage.app',
    measurementId: 'G-R0PC8NFLSV',
  );
}
